version: "3"

services:
  es-call-backend:
    build: ./backend
    restart: always
    container_name: es-call-backend
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/usr/es-call-backend"
    depends_on:
      - postgres
  
  es-call-frontend:
    build: ./frontend
    restart: always
    container_name: es-call-frontend
    ports:
      - "8080:8080"
    volumes:
      - "./frontend:/usr/es-call-frontend"
    depends_on:
      - es-call-backend

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database_script/generate_schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./backend/src/database_script/script_1.sql:/docker-entrypoint-initdb.d/2.sql

volumes:
  postgres_data: